# Generated by Django 6.0.1 on 2026-01-30 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_book_reader_alter_publishinghouse_established'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='slug',
            field=models.SlugField(default='dummy_slug', max_length=255),
            preserve_default=False,
        ),
    ]
