# Generated by Django 6.0.1 on 2026-01-30 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_book_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[('RM', 'Recommended'), ('ST', 'Started'), ('RD', 'Read'), ('AD', 'Abandonned'), ('RR', 'Rereading')], max_length=2),
        ),
    ]
