# Generated by Django 6.0.1 on 2026-01-31 10:03

import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_book_edition'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='publishinghouse',
            managers=[
                ('from_country', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveField(
            model_name='publishinghouse',
            name='location',
        ),
        migrations.AddField(
            model_name='publishinghouse',
            name='address',
            field=models.CharField(blank=True),
        ),
        migrations.AddField(
            model_name='publishinghouse',
            name='country',
            field=models.CharField(choices=[('PL', 'Poland'), ('UK', 'United Kingdom')], default='PL', max_length=2),
            preserve_default=False,
        ),
    ]
