# Generated by Django 6.0.2 on 2026-03-02 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_rename_author_book_authors'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='author',
            unique_together={('first_name', 'last_name')},
        ),
    ]
