# Generated by Django 6.0.2 on 2026-03-02 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_booklanguage_book_languages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booklanguage',
            name='code',
        ),
        migrations.AddField(
            model_name='booklanguage',
            name='country_sub_tag',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='booklanguage',
            name='language_sub_tag',
            field=models.CharField(blank=True, max_length=2),
        ),
    ]
