# Generated by Django 6.0.2 on 2026-03-02 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0011_remove_booklanguage_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='isbn',
            field=models.IntegerField(blank=True, max_length=13, null=True),
        ),
    ]
