# Generated by Django 6.0.2 on 2026-03-13 00:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0013_publication_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publications', to='books.book'),
        ),
    ]
