# Generated by Django 6.0.2 on 2026-03-26 00:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0014_alter_publication_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Countries',
            },
        ),
        migrations.AlterModelManagers(
            name='publishinghouse',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='publishinghouse',
            name='country',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='books.country'),
        ),
    ]
