# Generated by Django 6.0.2 on 2026-03-26 00:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0015_country_alter_publishinghouse_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publishinghouse',
            name='country',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='books.country'),
        ),
    ]
