# Generated by Django 6.0.2 on 2026-03-28 00:14

import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0016_alter_publishinghouse_country'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='publishinghouse',
            managers=[
                ('from_country', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
