# Generated by Django 6.0.2 on 2026-04-13 20:46

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0019_fragment_sentence_word_delete_textfragment'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='letter_count',
            field=models.GeneratedField(db_persist=True, expression=django.db.models.functions.text.Length('text'), output_field=models.IntegerField()),
        ),
    ]
